version: "3.3"
services:
  app:
    build:
      context: . #current directory
      dockerfile: Dockerfile #use the dockerfile called Dockerfile
    ports:
      - "8080:8080" #forward port from my app to the OS
    links: # app needs that redis is deployed successfully before app runs
      - redis
    environment: # Pass environment variables to the service
      REDIS_LOCAL_URL: "redis:6379" #the key is the same as the service name (redis)
    networks:
      - minesweepernet
  redis:
    image: "redis:alpine" #could be redis or redis alpine, is the same
    networks:
      - minesweepernet
    ports:
      - "6379:6379" #forward port from Redis to the OS
networks:
  minesweepernet: # network to communicate containers with each other